dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.7.3
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.7.3

compiler:
  solc:
    version: 0.8.17
    remappings:
      - '@openzeppelin/contracts=OpenZeppelin/openzeppelin-contracts@4.7.3/contracts'
      - '@openzeppelin/contracts-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.7.3/contracts'
