dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.8.2
  - OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.2

compiler:
  solc:
    version: 0.8.19
    remappings:
      - '@openzeppelin/contracts=OpenZeppelin/openzeppelin-contracts@4.8.2/contracts'
      - '@openzeppelin/contracts-upgradeable=OpenZeppelin/openzeppelin-contracts-upgradeable@4.8.2/contracts'
